datasources:
  postgres:
    url: jdbc:postgresql://localhost:5432/GitChat2
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
kestra:
  server:
    basicAuth:
      enabled: true
      username: "admin@gitchat.io"
      password: ${KESTRA_PASSWORD}
  repository:
    type: postgres
  storage:
    type: local
    local:
      basePath: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: "/tmp/gitchat-wd/tmp"
  url: "http://localhost:3000/"